Updates nbs markup
aws-samples/sagemaker-studio-emr pull request #33
Opened 2022-10-31 23:48 UTC by nc24

*Description of changes:* updated  markup 2 notebooks for labs 2 and 3. In lab 2, added message to ignore warnings when running import/ and in lab 3 added reference to connect to EMR cluster similar to lab2

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-14 22:01 UTC, seanpmorgan requested changes

2022-11-14 22:01 UTC, seanpmorgan commented on workshop/02_SentimentAnalysis/00_sparkmagic-sentiment-analysis.ipynb
> +    "Please ignore warnings about **PkgResourceDeprecation** and **invalid version** and **sagemaker.deprecations** when you run the cell below\n"
This appears to be fixed in the most recent versions of the kernel. Can you confirm?
![image](https://user-images.githubusercontent.com/18154355/201776478-79bef501-866f-479d-a3c6-9a74a5397650.png)

2022-11-14 22:01 UTC, seanpmorgan commented on workshop/03_TimeSeries/00_forecasting_with_deepAR.ipynb
> +   "display_name": "Python 3 (ipykernel)",
```suggestion
   "display_name": "PySpark (SparkMagic)",
```

2022-11-14 22:01 UTC, seanpmorgan commented on workshop/03_TimeSeries/00_forecasting_with_deepAR.ipynb
> +   "name": "python3"
```suggestion
   "name": "pysparkkernel__SAGEMAKER_INTERNAL__arn:aws:sagemaker:us-west-2:236514542706:image/sagemaker-sparkmagic"
```

2022-11-14 22:01 UTC, seanpmorgan commented on workshop/03_TimeSeries/00_forecasting_with_deepAR.ipynb
> +    "name": "ipython",
```suggestion
    "name": "python",
```

2022-11-14 22:01 UTC, seanpmorgan commented on workshop/03_TimeSeries/00_forecasting_with_deepAR.ipynb
> +   "version": "3.9.12"
```suggestion
   "name": "pyspark",
   "pygments_lexer": "python3",
```

2022-11-23 01:24 UTC, nc24 commented
approved

2022-11-23 01:24 UTC, closed without merging